---
title: "get_coordinates"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{get_coordinates}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(openjourney)
library(tidyverse)
library(tidygeocoder)
```


```{r}

library(XML)
library(xml2)
library(httr)

long_or <- 8.39
lat_or <- 47.34

long_dest <- 7.45
lat_dest <- 46.9

token1 <- paste("Bearer", "57c5dbbbf1fe4d000100001863396e06bcc5472eab6cacd76e44d91e", sep = " ")

```

```{r}
coords <- geo(address = c("Zürich Schwamendingerplatz, Switzerland",
"Bahnhof Stettbach, Switzerland"),
method ='osm')

time <- paste0(Sys.Date(),"T08:34:40")

ojp <- get_ojp_time(
 origin=c(coords[1,]$long,coords[1,]$lat),
 destination=c(coords[2,]$long,coords[2,]$lat,
               time=time)
)

response
```

```{r}
library(tidygeocoder)

coords2 <- geo(address = c("Zürich Schwamendingerplatz, Switzerland",
                          "Zürich Stadelhofen, Switzerland",
                          "Uster Bahnhof, Switzerland",
                          "Bern Hauptbahnhof, Switzerland",
"Bahnhof Stettbach, Switzerland"),
method ='osm')

time <- paste0(Sys.Date(),"T08:34:40")

# test mit einer Destination
triptimes99 <- map_dfr(c(1,54,850), ~get_ojp_time(
                               origin=c(coords[.x,]$lon,coords[.x,]$lat),
                               destination=c(coords2[5,]$long,coords2[5,]$lat),
                               time=time)
                              )

triptimes99b <- map_dfr(1:987, ~get_ojp_time(
                               origin=c(coords[.x,]$lon,coords[.x,]$lat),
                               destination=c(coords2[5,]$long,coords2[5,]$lat),
                               time=time,
                               sys.sleep=5)
                              )

saveRDS(triptimes99b,"trips.RDS")


# safe version
safe_ojp <- possibly(get_ojp_time, otherwise=NA)

triptimes2 <- map_dfr(seq(1,851,50), ~safe_ojp(origin=c(coords$lon[.x],coords$lat[.x]),
                              destination=c(coords2[5,]$long,coords2[5,]$lat,
                                            time=time,
                                            sys.sleep=5))
  )


# Funktioniert
triptimes2 <- map_dfr(1:987, ~safe_ojp(origin=c(coords$lon[.x],coords$lat[.x]),
                              destination=c(coords2[5,]$long,coords2[5,]$lat,
                                            time=time,
                                            sys.sleep=5))
  )

saveRDS(triptimes99b,"trips.RDS")


#problematische koordinate -> 57
triptimes2[[57]]

map(triptimes2,3)

# 1:nrow(coords) : Fehler:

triptimes3 <- map_dfr(1:70, ~safe_ojp(
                               origin=c(coords$lon[.x],coords$lat[.x]),
                              destination=c(coords2[5,]$long,coords2[5,]$lat))
                              )




# triptimes2[1]

```

