---
title: "Get Tripduration"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{get tripduration}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(openjourney)
library(tidyverse)
library(sf)
library(tidygeocoder)

# TODO<
#   add time to results dataframe
```

```{r}
# get coordinates of some locations
coords <- geo(address = c("Zürich Schwamendingerplatz, Switzerland",
                          "Zürich Stadelhofen, Switzerland",
                          "Uster Bahnhof, Switzerland",
                          "Bern Hauptbahnhof, Switzerland",
"Bahnhof Stettbach, Switzerland"),
method ='osm')

token1 <- paste("Bearer", "57c5dbbbf1fe4d000100001842c323fa9ff44fbba0b9b925f0c052d1", sep = " ")
```

```{r eval=FALSE, echo=TRUE}
trips <- get_tripduration(auth="your_token",
                                  origin=list(coords$long[1:4],coords$lat[1:4]),
                                  # origin_id=coords$address[1:4],
                                  destination=c(coords[5,]$long,coords[5,]$lat),
                                  # destination_id=coords$address[5],
                                  time="2021-03-13T08:34:40",
                                  sys.sleep=5)
                              
```

```{r eval=TRUE, echo=FALSE}
# by hand
# origin <- list(c(8.572164,47.40459),
#                c(8.59557,47.39675))
#
# destination <- c(7.45,46.9)

destination <- c(7.45,46.9)
# or with tidygeocoder
coords_list <- coords %>% 
                select(long,lat) %>% 
                purrr::transpose()


# token1 <- "Bearer 57c5dbbbf1fe4d0001000018c73945187db94eb1a26eff483259d2b4"

trips <- get_tripduration(auth=token1,
                          origin=coords_list,
                          # origin_id = coords$address[1:4],
                          destination=destination,
                          # destination_id=coords$address[5],
                          time="2021-03-23T08:34:40",
                          sys.sleep=5)

# Error: '{ "error": "Access to this API has been disallowed" }'
# %>% 
#   select(-destination) %>% 
#   plot()
```
# Plot trips
```{r}
ggplot(trips, aes(duration_min,trip_id,size=transfers, fill=transfers))+
  geom_col(position="dodge")+
  theme_minimal()+
  scale_fill_viridis_d()
```

